.TH "Obtaining information about a running call: sound volumes, quality indicators" 3 "Mon Feb 6 2012" "Version 3.5.0" "liblinphone" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Obtaining information about a running call: sound volumes, quality indicators \- 
.SS "Functions"

.in +1c
.ti -1c
.RI "float \fBlinphone_call_get_play_volume\fP (LinphoneCall *call)"
.br
.ti -1c
.RI "float \fBlinphone_call_get_record_volume\fP (LinphoneCall *call)"
.br
.ti -1c
.RI "float \fBlinphone_call_get_current_quality\fP (LinphoneCall *call)"
.br
.ti -1c
.RI "float \fBlinphone_call_get_average_quality\fP (LinphoneCall *call)"
.br
.in -1c
.SH "Detailed Description"
.PP 
When a call is running, it is possible to retrieve in real time current measured volumes and quality indicator'\&. 
.SH "Function Documentation"
.PP 
.SS "float linphone_call_get_play_volume (LinphoneCall *call)"Returns the measured sound volume played locally (received from remote) It is expressed in dbm0'\&. < Lowest measured that can be returned'\&. 
.SS "float linphone_call_get_record_volume (LinphoneCall *call)"Returns the measured sound volume recorded locally (sent to remote) It is expressed in dbm0'\&. < Lowest measured that can be returned'\&. 
.SS "float linphone_call_get_current_quality (LinphoneCall *call)"Obtain real-time quality rating of the call
.PP
Based on local RTP statistics and RTCP feedback, a quality rating is computed and updated during all the duration of the call'\&. This function returns its value at the time of the function call'\&. It is expected that the rating is updated at least every 5 seconds or so'\&. The rating is a floating point number comprised between 0 and 5'\&.
.PP
4-5 = good quality 
.br
 3-4 = average quality 
.br
 2-3 = poor quality 
.br
 1-2 = very poor quality 
.br
 0-1 = can't be worse, mostly unusable 
.br
.PP
\fBReturns:\fP
.RS 4
The function returns -1 if no quality measurement is available, for example if no active audio stream exist'\&. Otherwise it returns the quality rating'\&. 
.RE
.PP

.SS "float linphone_call_get_average_quality (LinphoneCall *call)"Returns call quality averaged over all the duration of the call'\&.
.PP
See \fBlinphone_call_get_current_quality()\fP for more details about quality measurement'\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for liblinphone from the source code'\&.
