.TH "Chat room and Messaging" 3 "Mon Feb 6 2012" "Version 3.5.0" "liblinphone" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Chat room and Messaging \- 
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct _LinphoneChatRoom \fBLinphoneChatRoom\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBLinphoneChatRoom\fP * \fBlinphone_core_create_chat_room\fP (\fBLinphoneCore\fP *lc, const char *to)"
.br
.ti -1c
.RI "void \fBlinphone_chat_room_destroy\fP (\fBLinphoneChatRoom\fP *cr)"
.br
.ti -1c
.RI "const \fBLinphoneAddress\fP * \fBlinphone_chat_room_get_peer_address\fP (\fBLinphoneChatRoom\fP *cr)"
.br
.ti -1c
.RI "void \fBlinphone_chat_room_send_message\fP (\fBLinphoneChatRoom\fP *cr, const char *msg)"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fB Exchanging text messages\fP 
.br
 Messages are sent using \fBLinphoneChatRoom\fP object'\&. First step is to create a \fBchat room \fP from a peer sip uri'\&. 
.PP
.nf
LinphoneChatRoom* chat_room = linphone_core_create_chat_room(lc,'sip:joe@sip\&.linphone\&.org');

.fi
.PP
.PP

.br
Once created, messages are sent using function \fBlinphone_chat_room_send_message()\fP '\&. 
.PP
.nf
linphone_chat_room_send_message(chat_room,'Hello world'); /*sending message*/

.fi
.PP
 
.br
Incoming message are received from call back \fBLinphoneCoreVTable'\&.text_received\fP 
.PP
.nf
void text_received(LinphoneCore *lc, LinphoneChatRoom *room, const LinphoneAddress *from, const char *message) {
        printf(' Message [%s] received from [%s] \n',message,linphone_address_as_string (from));
}

.fi
.PP
 
.br
 A complete tutorial can be found at : \fBChat room tutorial\fP 
.SH "Typedef Documentation"
.PP 
.SS "typedef struct _LinphoneChatRoom \fBLinphoneChatRoom\fP"A chat room is the place where text messages are exchanged'\&. 
.br
 Can be created by \fBlinphone_core_create_chat_room()\fP'\&. 
.SH "Function Documentation"
.PP 
.SS "\fBLinphoneChatRoom\fP* linphone_core_create_chat_room (\fBLinphoneCore\fP *lc, const char *to)"Create a new chat room for messaging from a sip uri like sip:joe@sip.linphone.org 
.PP
\fBParameters:\fP
.RS 4
\fIlc\fP \fBLinphoneCore\fP object 
.br
\fIto\fP destination address for messages 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBLinphoneChatRoom\fP where messaging can take place'\&. 
.RE
.PP

.SS "void linphone_chat_room_destroy (\fBLinphoneChatRoom\fP *cr)"Destructor 
.PP
\fBParameters:\fP
.RS 4
\fIcr\fP \fBLinphoneChatRoom\fP object 
.RE
.PP

.SS "const \fBLinphoneAddress\fP* linphone_chat_room_get_peer_address (\fBLinphoneChatRoom\fP *cr)"get peer address \fBassociated to \fP this \fBLinphoneChatRoom\fP 
.PP
\fBParameters:\fP
.RS 4
\fIcr\fP \fBLinphoneChatRoom\fP object 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBLinphoneAddress\fP peer address 
.RE
.PP

.SS "void linphone_chat_room_send_message (\fBLinphoneChatRoom\fP *cr, const char *msg)"send a message to peer member of this chat room'\&. 
.PP
\fBParameters:\fP
.RS 4
\fIcr\fP \fBLinphoneChatRoom\fP object 
.br
\fImsg\fP message to be sent 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for liblinphone from the source code'\&.
