.TH "Tutorials:" 3 "Mon Feb 6 2012" "Version 3.5.0" "liblinphone" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Tutorials: \- 
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBBasic buddy status notification\fP"
.br
.ti -1c
.RI "\fBChat room and messaging\fP"
.br
.ti -1c
.RI "\fBBasic call\fP"
.br
.ti -1c
.RI "\fBBasic registration\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for liblinphone from the source code'\&.
