.TH "_LinphoneCallLog" 3 "Mon Feb 6 2012" "Version 3.5.0" "liblinphone" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_LinphoneCallLog \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <linphonecore\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBLinphoneCallDir\fP \fBdir\fP"
.br
.ti -1c
.RI "\fBLinphoneCallStatus\fP \fBstatus\fP"
.br
.ti -1c
.RI "\fBLinphoneAddress\fP * \fBfrom\fP"
.br
.ti -1c
.RI "\fBLinphoneAddress\fP * \fBto\fP"
.br
.ti -1c
.RI "char \fBstart_date\fP [128]"
.br
.ti -1c
.RI "int \fBduration\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure representing a call log'\&. 
.SH "Field Documentation"
.PP 
.SS "\fBLinphoneCallDir\fP \fB_LinphoneCallLog::dir\fP"The direction of the call 
.SS "\fBLinphoneCallStatus\fP \fB_LinphoneCallLog::status\fP"The status of the call 
.SS "\fBLinphoneAddress\fP* \fB_LinphoneCallLog::from\fP"Originator of the call as a LinphoneAddress object 
.SS "\fBLinphoneAddress\fP* \fB_LinphoneCallLog::to\fP"Destination of the call as a LinphoneAddress object 
.SS "char \fB_LinphoneCallLog::start_date\fP[128]"Human readable string containg the start date 
.SS "int \fB_LinphoneCallLog::duration\fP"Duration of the call in seconds 

.SH "Author"
.PP 
Generated automatically by Doxygen for liblinphone from the source code'\&.
