.TH "/Users/chris/Code/Gargoyle/linphone-iphone/submodules/linphone/coreapi/ Directory Reference" 3 "Mon Feb 6 2012" "Version 3.5.0" "liblinphone" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/chris/Code/Gargoyle/linphone-iphone/submodules/linphone/coreapi/ Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBhelp\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBaddress\&.c\fP"
.br
.ti -1c
.RI "file \fBauthentication\&.c\fP"
.br
.ti -1c
.RI "file \fBcallbacks\&.c\fP"
.br
.ti -1c
.RI "file \fBchat\&.c\fP"
.br
.ti -1c
.RI "file \fBconference\&.c\fP"
.br
.ti -1c
.RI "file \fBec-calibrator\&.c\fP"
.br
.ti -1c
.RI "file \fBenum\&.c\fP"
.br
.ti -1c
.RI "file \fBenum\&.h\fP"
.br
.ti -1c
.RI "file \fBfonis\&.c\fP"
.br
.ti -1c
.RI "file \fBfriend\&.c\fP"
.br
.ti -1c
.RI "file \fBlinphone_tunnel\&.h\fP"
.br
.ti -1c
.RI "file \fBlinphonecall\&.c\fP"
.br
.ti -1c
.RI "file \fBlinphonecore\&.c\fP"
.br
.ti -1c
.RI "file \fBlinphonecore\&.h\fP"
.br
.ti -1c
.RI "file \fBlinphonecore_utils\&.h\fP"
.br
.ti -1c
.RI "file \fBlinphonefriend\&.h\fP"
.br
.ti -1c
.RI "file \fBlpconfig\&.c\fP"
.br
.ti -1c
.RI "file \fBlpconfig\&.h\fP"
.br
.ti -1c
.RI "file \fBlsd\&.c\fP"
.br
.ti -1c
.RI "file \fBmisc\&.c\fP"
.br
.ti -1c
.RI "file \fBofferanswer\&.c\fP"
.br
.ti -1c
.RI "file \fBofferanswer\&.h\fP"
.br
.ti -1c
.RI "file \fBpresence\&.c\fP"
.br
.ti -1c
.RI "file \fBprivate\&.h\fP"
.br
.ti -1c
.RI "file \fBproxy\&.c\fP"
.br
.ti -1c
.RI "file \fBsal\&.c\fP"
.br
.ti -1c
.RI "file \fBsal\&.h\fP"
.br
.ti -1c
.RI "file \fBsal_eXosip2\&.c\fP"
.br
.ti -1c
.RI "file \fBsal_eXosip2\&.h\fP"
.br
.ti -1c
.RI "file \fBsal_eXosip2_presence\&.c\fP"
.br
.ti -1c
.RI "file \fBsal_eXosip2_sdp\&.c\fP"
.br
.ti -1c
.RI "file \fBsiplogin\&.c\fP"
.br
.ti -1c
.RI "file \fBsipsetup\&.c\fP"
.br
.ti -1c
.RI "file \fBsipsetup\&.h\fP"
.br
.ti -1c
.RI "file \fBtest_ecc\&.c\fP"
.br
.ti -1c
.RI "file \fBtest_lsd\&.c\fP"
.br
.in -1c
